docker/supervisord.conf
pypi/src/briefer/main.py

- Adds a message telling the image is being pulled
- Capture CTRL-C to stop the container before exiting

Improve PyPI startup script

---

README.md

docs: nice message for windows users :)

---

apps/api/src/python/visualizations.ts
apps/api/src/yjs/v2/executors/blocks/visualization.test.ts
apps/api/src/yjs/v2/executors/blocks/visualization.ts
apps/web/src/components/v2Editor/customBlocks/visualization/FilterSelector.tsx
apps/web/src/components/v2Editor/customBlocks/visualization/MultiCombobox.tsx
apps/web/src/components/v2Editor/customBlocks/visualization/index.tsx
packages/types/src/index.ts

https://github.com/user-attachments/assets/5566608a-d0a6-41ba-8590-a15dc4d724d3

feat: Introduce ability to use variables in filters

---

.github/CONTRIBUTING.md
SECURITY.md

Hello Lucas (s)
I'm happy to say that I found a way to contribute to the briefer. For many years I was a data and BI analyst and I've worked with several tools like the briefer. First of all, I want to congratulate you on the project.
I took the initiative to submit two changes:
* The first adds a SECURITY.md file to the repo indicating how users should report vulnerabilities.
* The second adds this security policy information to CONTRIBUITING.md.
I would be happy if you could review them and merge them if it makes sense.
Thank you very much.

docs: Added how to send Vunerability Reports

---

docker/Dockerfile
docker/setup/jupyter.py

Fix pip install

---

apps/web/src/components/forms/user.tsx

fix: not disabling save button while adding user

---

apps/web/src/components/Files.tsx

Adding spinner to indicate when the user delete a file.
Issue: #62

feat: spin render when deleting file

---

docs/DEPLOYMENT_GCP.md

Adds Google Cloud Platform (GCP) deployment guide.
No, this PR is just for add documentation guide.

doc: add gcp deployment guide

---

apps/web/package.json
apps/web/src/components/v2Editor/Title.tsx
apps/web/src/components/v2Editor/customBlocks/richText/FormattingToolbar.tsx
apps/web/src/components/v2Editor/customBlocks/richText/index.tsx
apps/web/src/styles/globals.css
yarn.lock

Added the task list and task items to the editor using tiptap extensions.
Closes #16 
To add a task list use `[ ]` or `[x]`, or through the window on focus.

Added tasklist and taskitems to the editor

---

apps/api/src/config/base.ts
apps/api/src/properties.ts
apps/web/src/components/v2Editor/EditWithAIForm.tsx
apps/web/src/components/v2Editor/customBlocks/python/index.tsx
apps/web/src/components/v2Editor/customBlocks/sql/index.tsx
apps/web/src/pages/workspaces/[workspaceId]/settings/index.tsx
packages/types/src/index.ts
pypi/src/briefer/main.py
start.sh

enable custom OAI key by default

---

ai/requirements.txt
apps/api/jupyter-requirements.txt
apps/api/src/auth/token.ts
apps/api/src/datasources/index.ts
apps/api/src/datasources/snowflake.ts
apps/api/src/datasources/structure.ts
apps/api/src/python/query/index.ts
apps/api/src/python/query/snowflake.ts
apps/api/src/python/query/sqlalchemy.ts
apps/api/src/python/writeback/index.ts
apps/api/src/v1/workspaces/workspace/data-sources/data-source.ts
apps/api/src/v1/workspaces/workspace/data-sources/index.ts
apps/web/src/components/DataSourceIcons.tsx
apps/web/src/components/DataSourcesList.tsx
apps/web/src/components/forms/snowflake.tsx
apps/web/src/hooks/useDatasource.ts
apps/web/src/pages/workspaces/[workspaceId]/data-sources/edit/[dataSourceId].tsx
apps/web/src/pages/workspaces/[workspaceId]/data-sources/new/index.tsx
apps/web/src/pages/workspaces/[workspaceId]/data-sources/new/snowflake.tsx
apps/web/src/pages/workspaces/[workspaceId]/environments/current/index.tsx
packages/database/prisma/migrations/20240928163915_introduce_snowflake_datasource/migration.sql
packages/database/prisma/migrations/20241007030843_introduce_snowflake_data_source/migration.sql
packages/database/prisma/migrations/20241007033043_introduce_snowflake_data_source/migration.sql
packages/database/prisma/schema.prisma
packages/database/src/datasources/index.ts
packages/database/src/datasources/snowflake.ts

Added the Snowflake datasource connector and performed manual testing.
This PR Closes #46
- Integrated the Snowflake datasource into the database and backend/frontend code, using the sqlalchemy-snowflake library to maintain consistency with other datasources.
- Tested creating a Snowflake datasource.
- Tested editing the Snowflake datasource.
- Tested pinging the datasource from the frontend (verified both failure and success cases).
- Verified the Snowflake schema functionality.
- Tested creating SQL cells using the Snowflake datasource.
- Tested running queries with the Snowflake datasource.
- Tested stopping query execution.
**Note: I didn't see any PR templates, so I provided details on what I added and tested. If you need additional information or screenshots, feel free to let me …

Added the snowflake datasource

---

apps/api/src/datasources/athena.ts
apps/api/src/datasources/bigquery.ts
apps/api/src/datasources/index.ts
apps/api/src/datasources/mysql.ts
apps/api/src/datasources/oracle.ts
apps/api/src/datasources/psql.ts
apps/api/src/datasources/redshift.ts
apps/api/src/datasources/snowflake.ts
apps/api/src/datasources/sqlserver.ts
apps/api/src/datasources/trino.ts
apps/api/src/python/query/index.ts
apps/api/src/v1/workspaces/workspace/data-sources/data-source.ts
apps/api/src/v1/workspaces/workspace/data-sources/index.ts
apps/api/src/websocket/workspace/data-sources.ts
apps/web/src/components/DataSourcesList.tsx
apps/web/src/hooks/useDatasource.ts
apps/web/src/pages/workspaces/[workspaceId]/data-sources/new/athena.tsx
apps/web/src/pages/workspaces/[workspaceId]/data-sources/new/bigquery.tsx
apps/web/src/pages/workspaces/[workspaceId]/data-sources/new/mysql.tsx
apps/web/src/pages/workspaces/[workspaceId]/data-sources/new/oracle.tsx
apps/web/src/pages/workspaces/[workspaceId]/data-sources/new/postgresql.tsx
apps/web/src/pages/workspaces/[workspaceId]/data-sources/new/redshift.tsx
apps/web/src/pages/workspaces/[workspaceId]/data-sources/new/snowflake.tsx
apps/web/src/pages/workspaces/[workspaceId]/data-sources/new/sqlserver.tsx
apps/web/src/pages/workspaces/[workspaceId]/data-sources/new/trino.tsx

[Screencast from 2024-09-17 08-20-55.webm](https://github.com/user-attachments/assets/d1de98f3-226d-426b-a312-ebcf5ff6385b)
Issue: #70

feat: adding a message while loading a new data source

---

apps/api/src/python/visualizations.ts
apps/api/src/yjs/v2/executors/blocks/visualization.test.ts
apps/web/src/components/v2Editor/customBlocks/python/index.tsx
apps/web/src/components/v2Editor/customBlocks/visualization/VisualizationControls.tsx
apps/web/src/components/v2Editor/customBlocks/visualization/YAxisPicker.tsx
packages/editor/src/blocks/visualization.ts
packages/types/src/index.ts

fix multi-y-axis naming

---

pypi/src/briefer/main.py

@vieiralucas can you please release to `pip` and test downloading from there?
I ended up using a docker-like output instead of bars given it's more precise, even though it may bug out when resizing the terminal.

show pip docker image download progress

---

apps/web/src/components/v2Editor/DragHandle.tsx
apps/web/src/components/v2Editor/index.tsx
packages/editor/src/blocks/index.ts

show 'run this block' option in drag handle

---

apps/web/src/components/v2Editor/customBlocks/python/index.tsx
apps/web/src/components/v2Editor/customBlocks/sql/SQLResult.tsx

Better error indication on collapsed python results

---

apps/api/src/python/query/athena.ts
apps/api/src/python/query/index.ts
apps/api/src/yjs/v2/executors/blocks/sql.test.ts
apps/api/src/yjs/v2/executors/blocks/sql.ts
apps/web/src/components/v2Editor/customBlocks/sql/SQLQueryConfigurationButton.tsx
apps/web/src/components/v2Editor/customBlocks/sql/index.tsx
packages/editor/src/blocks/sql.ts
packages/editor/src/component.ts
packages/types/src/index.ts

Athena reuse query results

---

apps/web/src/components/DashboarNotebookGroupButton.tsx
apps/web/src/components/Dashboard/DashboardView.tsx
apps/web/src/components/Dashboard/index.tsx
apps/web/src/components/EllipsisDropdown.tsx
apps/web/src/components/EnvBar.tsx
apps/web/src/components/PrivateDocumentPage.tsx
apps/web/src/components/v2Editor/index.tsx
apps/web/src/pages/workspaces/[workspaceId]/environments/current/variables.tsx

Viewers had a weird experience because we were showing them a bunch of stuff they couldn't use.

Viewer UI updates

---

chart/templates/ai-deployment.yaml

Change default AI port in the Helm chart to 4000

---

chart/templates/api-deployment.yaml
chart/templates/jupyter-statefulset.yaml
chart/values.yaml

Added ALLOW_HTTP to helm chart api-development
Fixed livenessProbe in jupyter-statefulset

feat: added ALLOW_HTTP to helm-chart

---

apps/api/src/v1/workspaces/workspace/documents/document/settings.ts
apps/api/src/yjs/v2/executors/blocks/sql.test.ts
apps/api/src/yjs/v2/executors/blocks/sql.ts
apps/api/src/yjs/v2/executors/run-all.ts
apps/api/src/yjs/v2/observers/blocks/sql.test.ts
apps/api/src/yjs/v2/observers/blocks/sql.ts
apps/web/src/components/PageSettingsPanel.tsx
apps/web/src/components/v2Editor/CodeEditor/index.tsx
apps/web/src/components/v2Editor/customBlocks/sql/index.tsx
apps/web/src/hooks/useDocument.ts
apps/web/src/hooks/useDocuments.tsx
packages/database/prisma/migrations/20241106182901_add_run_sql_selection_to_document_table/migration.sql
packages/database/prisma/schema.prisma
packages/editor/src/blocks/sql.ts
packages/editor/src/component.ts

introduce ability to run only selected sql

---

apps/web/src/components/AxisSelector.tsx
apps/web/src/components/v2Editor/customBlocks/sql/Table.tsx

add icons to sql table columns

---

apps/web/src/components/PrivateDocumentPage.tsx
apps/web/src/components/RunAllV2.tsx
apps/web/src/components/v2Editor/index.tsx

scroll into failed block when run all fails

---

apps/web/src/components/v2Editor/CodeEditor/index.tsx

Close #172 
Close #204 
Note that #204 was actually #172

fix breaking editor when switching pages while there's a diff in a page

---

apps/web/src/hooks/useSchemaList.ts

Close #240 
Also fixes duplicating schemas and tables due to trying to mutate an immutable set (pic related)

Fix explorer order

---

apps/web/src/components/DashboarNotebookGroupButton.tsx
apps/web/src/components/Files.tsx
apps/web/src/components/Layout.tsx
apps/web/src/components/ReusableComponents.tsx
apps/web/src/components/v2Editor/customBlocks/sql/Table.tsx

Close #220
and fix a few other things that annoy me.

Minor UI fixes

---

apps/web/src/hooks/useSchemaList.ts

fix schema explorer toggle opened/collapsed on search

---

apps/web/src/components/v2Editor/CodeEditor/index.tsx

use four spaces for indentation on codeblocks

---

apps/web/src/components/Dashboard/GridElement.tsx
apps/web/src/components/DocumentsTree.tsx

Also noticed that resizing was broken due to the scrollbar, oddly enough.
+ added a minor positioning fix for context menus on the doc tree

Fix showing tooltips on visualizations within dashboard

---

README.md

Small PR - Commit 384fbe0020a756ba7aa15682875a30d15e927475 moved the contributing guide. This PR adjusts sources to changes.

update contributing guide reference

---

apps/api/src/v1/workspaces/workspace/data-sources/data-source.ts
apps/api/src/v1/workspaces/workspace/data-sources/index.ts
apps/web/src/components/DataSourcesList.tsx
apps/web/src/components/v2Editor/index.tsx
apps/web/src/hooks/useDatasources.tsx
apps/web/src/pages/workspaces/[workspaceId]/data-sources/index.tsx
packages/database/prisma/migrations/20241209175400_add_is_default_to_datasources/migration.sql
packages/database/prisma/schema.prisma
packages/database/src/datasources/athena.ts
packages/database/src/datasources/bigquery.ts
packages/database/src/datasources/databrickssql.ts
packages/database/src/datasources/mysql.ts
packages/database/src/datasources/oracle.ts
packages/database/src/datasources/psql.ts
packages/database/src/datasources/redshift.ts
packages/database/src/datasources/snowflake.ts
packages/database/src/datasources/sqlserver.ts
packages/database/src/datasources/trino.ts

Not ready until #284 is merged

introduce ability to make a datasource the default one

---

chart/Chart.yaml
chart/templates/api-deployment.yaml
chart/values.yaml

fix default values of helm chart enforcing pg ssl

---

docker/setup/setup.py

use all POSTGRES_ variables in migration too

---

.dockerignore
docker/Dockerfile
docker/setup/ai.py
docker/supervisord.conf

add ai to monolith docker image

---

apps/api/src/v1/workspaces/workspace/documents/document/settings.ts
apps/web/src/components/Dashboard/index.tsx
apps/web/src/components/PageSettingsPanel.tsx
apps/web/src/components/PrivateDocumentPage.tsx
apps/web/src/hooks/useDocument.ts
apps/web/src/hooks/useDocuments.tsx
apps/web/src/hooks/useSideBar.tsx
apps/web/src/pages/workspaces/[workspaceId]/documents/[documentId]/dashboard/index.tsx
apps/web/src/pages/workspaces/[workspaceId]/documents/[documentId]/index.tsx
apps/web/src/pages/workspaces/[workspaceId]/documents/[documentId]/notebook/index.tsx
docs/settings/page-settings.mdx
packages/database/prisma/migrations/20250104200947_share_links_without_sidebar/migration.sql
packages/database/prisma/schema.prisma

@vieiralucas can you E2E test this too?

allow share links with collapsible sidebar param

---

apps/api/src/python/query/index.ts
apps/api/src/v1/workspaces/workspace/documents/document/queries/query/index.ts
apps/api/src/yjs/v2/executor/sql.ts
apps/web/src/components/v2Editor/customBlocks/sql/SQLResult.tsx
apps/web/src/components/v2Editor/customBlocks/sql/Table.tsx
apps/web/src/components/v2Editor/customBlocks/sql/index.tsx
packages/editor/src/blocks/sql.ts
packages/types/src/index.ts

introduce sorting by column to sql block result

---

apps/web/src/components/v2Editor/FormatSQLButton.tsx
apps/web/src/components/v2Editor/customBlocks/sql/index.tsx
packages/editor/package.json
packages/editor/src/blocks/sql.ts
yarn.lock

see: https://github.com/briefercloud/briefer/issues/330

feat: allow format sql code

---

apps/web/src/components/Files.tsx

This PR adds a quick search on files list, aims to help users that have many files.
Closes https://github.com/briefercloud/briefer/issues/227

Add a quick search on files list
