apps/web/src/components/v2Editor/index.tsx
apps/web/src/hooks/useV2CodeEditor.ts

When a code block is inserted, the editor switches to insert mode, which
previously caused the scroll view to adjust slightly to ensure the current
line was always visible. Now, we've changed the behavior to only scroll if
the current line is actually off-screen. This prevents unnecessary scrolling
after inserting blocks since the view already adjusts when the block is
inserted.

 fix: Unnecessary scrolling after code block insert

---

apps/api/src/auth/base.ts
apps/api/src/auth/index.ts
apps/api/src/config/base.ts
apps/web/src/hooks/useSessionRedirect.ts
apps/web/src/pages/_app.tsx
docs/DEPLOYMENT.md
pypi/src/briefer/main.py

Closes #23 
Notice that this is also removing the `sessionExpiry` cookie because it needs `TLD` to be set which defeats the idea of running Briefer without a domain.
The drawback of removing that is minor, it is only used at the frontend to know when the `token` is expired and move user back to login screen automatically. We should implement that using another strategy.

feat: Introduce ALLOW_HTTP env var that allows authentication to work without https

---

apps/web/src/components/SubscriptionBadge.tsx

SubscriptionBadge had an inconsistency for open-source version that currently doesn't support Snapshots.
Updated the SubscriptionBadge open-source settings: snapshots to false

update: SubscriptionBadge open-source settings

---

docker-compose.dev.yaml

The docker compose dev was missing a migration. Therefore the API wasn't able to initialize.

fix missing migration on docker compose dev

---

start-dev.sh

The `start-dev.sh` script was using the frontend URL as the API URL. As a consequence, the frontend was redirecting the user to a route that did not exist in the frontend itself during authentication.

fix generating incorrect port when running on dev mode

---

.dockerignore
README.md
apps/api/src/websocket/index.ts
apps/api/src/yjs/v2/index.ts
apps/web/Dockerfile
apps/web/package.json
apps/web/src/hooks/useWebsocket.tsx
apps/web/src/utils/env.ts
apps/web/start.sh
docker-compose.yaml
docker/Dockerfile
docker/setup/api.py
docker/setup/setup.py
docker/setup/web.py
docker/start-nginx.sh
docker/supervisord.conf
docs/DEPLOYMENT.md
nginx/nginx.conf
pypi/src/briefer/main.py
start-dev.sh
start.sh

@lucasfcosta can you review and improve the docs?
I made some changes there but maybe now we can write it differently.

Simplify deployment by removing the need for any env vars by default

---

apps/web/src/hooks/useQueryArgs.ts

https://jsbenchmark.com/#eyJjYXNlcyI6W3siaWQiOiJNLUtwWXBqNUU5akRrTHVPRW41emsiLCJjb2RlIjoiJ2ZvbycubWF0Y2goL2Jhci8pOyIsImRlcGVuZGVuY2llcyI6W10sIm5hbWUiOiInZm9vJy5tYXRjaCgvYmFyLyk7In0seyJpZCI6IkFSUDNBVkVfQ0ZPd05tazNDeXZoXyIsImNvZGUiOiIvYmFyLy5leGVjKCdmb28nKTsiLCJkZXBlbmRlbmNpZXMiOltdLCJuYW1lIjoiL2Jhci8uZXhlYygnZm9vJyk7In1dLCJjb25maWciOnsibmFtZSI6IiIsInBhcmFsbGVsIjp0cnVlLCJkYXRhQ29kZSI6IiIsImdsb2JhbFRlc3RDb25maWciOnsiZGVwZW5kZW5jaWVzIjpbXX19fQ

Prefer "RegExp.exec" over "String.match"

---

apps/web/src/components/v2Editor/customBlocks/python/PythonOutput.tsx
apps/web/src/components/v2Editor/customBlocks/python/index.tsx
apps/web/src/components/v2Editor/customBlocks/visualization/VisualizationView.tsx
apps/web/src/components/v2Editor/customBlocks/visualization/index.tsx
apps/web/src/utils/file.ts

Adds #18
Currently, exporting works for all Briefer's visualization blocks and Python's graph outputs in the Notebook tab.
- The only case where the `renderer` is `svg` is in the Dashboard's block list, where the export button is not visible
- [Can I Use `a[download]`](https://caniuse.com/?search=a.download)
- Briefer itself doesn't support Internet Explorer, so we don't need to do this

Add PNG export for Notebook's visualization blocks

---

apps/api/src/python/query/index.ts

Issue Fix: #15
This issue arises because JSON can't serialize DATE types by default. To fix this, we need to handle it in a custom way by converting DATE and DATETIME objects to isoformat() before serialization.
The root cause of the issue is that whenever we have a DataFrame (df), it tries to store the data in a format suitable for visualization. When storing it in JSON format, serialization is required.
The vis.to_json function itself works perfectly fine.
Let me know if you'd like any further adjustments!

fix serialization issue with date dtypes of df

---

apps/web/src/components/v2Editor/customBlocks/python/PythonOutput.tsx

Before            |  After
:-------------------------:|:-------------------------:

Prevent unnecessary right align in PythonOutput component

---

apps/web/src/components/forms/FileUploadInput.tsx

I added a prevent default to avoid the file chooser to opens twice when selecting a BigQuery service.
Issue: #61

Preventing file chooser to opens twice

---

apps/web/src/components/v2Editor/customBlocks/python/PythonOutput.tsx

Align only the PNG button in the PythonOutput component

---

apps/web/src/components/v2Editor/customBlocks/richText/index.tsx

This changes how the positioning of [Tippy](https://kabbouchi.github.io/tippyjs-v4-docs/getting-started/) is calculated and fixes the bug of the tooltip still showing after clicking outside the text block.

hide tooltip when something inside it is open

---

apps/web/src/components/v2Editor/customBlocks/visualization/YAxisPicker.tsx

The previous terminology was confusing as reported by a customer - I agree with that feedback.

change 'color by' label to Group By

---

apps/web/src/components/DashboarNotebookGroupButton.tsx
apps/web/src/components/v2Editor/EditWithAIForm.tsx
apps/web/src/components/v2Editor/customBlocks/python/index.tsx
apps/web/src/components/v2Editor/customBlocks/sql/index.tsx

Fix minor visual issues that bother me a lot

---

apps/api/src/python/writeback/bigquery.ts

Fixes an error that would happen when an insert with no columns to ignore would end up not being able to get the number of affected rows and thus would yield an empty iterator.

Fix empty insert error

---

apps/api/src/config/base.ts
apps/api/src/index.ts
chart/Chart.yaml
chart/templates/api-deployment.yaml
chart/values.yaml
docker/setup/api.py
docs/deployment/troubleshooting.mdx
packages/database/src/index.ts

> A quick look at the pg-connection-string tests seems to suggest that `sslmode: prefer` is parsed the same as `ssl = true`;
> https://github.com/sequelize/sequelize/discussions/16287#discussioncomment-6480038

SSL configs equal to prefer in sslmode

---

apps/web/src/components/DocumentsTree.tsx
apps/web/src/components/DragLayer.tsx
apps/web/src/components/Layout.tsx
apps/web/src/components/v2Editor/customBlocks/python/PythonOutput.tsx
apps/web/src/components/v2Editor/index.tsx
packages/types/src/index.ts

Fixes the drag preview for the editor and also adds "scroll on drag".
PS: I also updated the plotly import because I was having issues with it rendering on the server side.
See https://github.com/plotly/react-plotly.js/issues/272
Not sure why this started happening now though

Fix drag preview

---

docs/deployment/gcp.mdx

Fix GCP deployment documentation table of contents, that was pointing to invalid anchor links.

docs: update anchor links in GCP deployment table of contents

---

.github/contributing/CONTRIBUTING.md

This PR aims to improve documentation by fixing head links and fixing dev mode image path.
Before:
After:

docs: fix markdown heading link and dev mode image

---

docker/setup/api.py

While self-hosting Briefer, we encountered an issue where it couldn't find the RDS database we were connecting to. It turned out that the problem was due to Briefer always trying to access a local Postgres instance instead of using the POSTGRES_HOSTNAME provided as an environment variable. Happy to adjust the code in case you want to fix it using a different approach!

fix: Access env var
